name: Python Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: raju2525

    - name: Run tests
      run: |
        python -m unittest discover tests
      working-directory: raju2525

    - name: Build
      run: |
        # Replace this with your build command
        python build.py
      working-directory: raju2525

    - name: Publish
      run: |
        # Replace this with your publish command
        python publish.py
      working-directory: raju2525
